default: &default
  adapter: postgresql
  pool: 25
  timeout: 5000

development:
  <<: *default
  database: group_movie_queue_development

test:
  <<: *default
  database: group_movie_queue_test

production:
  <<: *default
  database: group_movie_queue_production