# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5c73d6a140fa7315e58140f123a2f1f3665c781e862264634b9fc56c8e386c14c7d35ced3439a9d072e2e7cac602409b4c06e4e86a8243698ce8f2d875849d9

test:
  secret_key_base: 024407f3bbd09ea48ab3474eab175ed1d1b6c8af8146652f4b83816be32cffb9ac285fc32d512f8e75c76f003e2637a19931d391a56b2faffe59f06c4a05c146

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
